# Font
font-family = MesloLGS NF

# Color Scheme
theme = catppuccin-mocha.conf

# Background
background-opacity = 0.97
background-blur = 16

# Window
window-padding-x = 6
window-padding-y = 6
window-padding-balance = true
window-decoration = auto

# Cursor
cursor-opacity = 1
cursor-invert-fg-bg = false

# Application Behavior
quit-after-last-window-closed = true
