[ids]
k:3434:0a00

[main]
leftmeta = layer(command)
rightmeta = layer(command)
leftalt = layer(option)
rightalt = layer(option)

[command:C]
left = home
right = end

[option:A]
left = C-left
right = C-right
